# Generated by Django 3.2.4 on 2021-06-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='User',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='Password'),
            preserve_default=False,
        ),
    ]
