# Generated by Django 3.2.4 on 2021-06-17 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingbody',
            name='user',
        ),
        migrations.AddField(
            model_name='bill',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user', verbose_name='Código de Usere'),
            preserve_default=False,
        ),
    ]
