# Generated by Django 3.2.4 on 2021-06-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='code',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
